[project]
name = "sistema-cleoferr"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "dotenv>=0.9.9",
    "mysql-connector-python>=9.5.0",
    "python-dotenv>=1.2.1",
    "supabase>=2.25.1",
]
