[project]
name = "sistema-cleoferr"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = "3.11"
dependencies = [
    "dotenv==0.9.9",
    "streamlit==1.31.1",
    "supabase==2.25.1",
]
