[project]
name = "sistema-cleoferr"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10,<3.12"

dependencies = [
    "streamlit==1.31.1",
    "supabase==2.27.0",
    "python-dotenv==1.0.1"
]
