[project]
name = "sistema-cleoferr"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "python-dotenv>=1.2.1",
    "streamlit>=1.52.2",
    "supabase>=2.25.1",
    "cryptography<46",
    "cffi<2"
]